# Generated by Django 4.0.4 on 2022-05-11 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockSymbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('display_symbol', models.CharField(max_length=32)),
                ('figi', models.CharField(max_length=64)),
                ('isin', models.CharField(max_length=32, null=True)),
                ('mic', models.CharField(max_length=32)),
                ('share_class_figi', models.CharField(max_length=64)),
                ('symbol', models.CharField(max_length=32)),
                ('symbol2', models.CharField(max_length=32)),
                ('type', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('change', models.DecimalField(decimal_places=2, max_digits=10)),
                ('percent_change', models.DecimalField(decimal_places=2, max_digits=10)),
                ('high_price_of_the_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('low_price_of_the_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('open_price_of_the_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('previous_close_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('time_stamp', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock_symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.stocksymbol')),
            ],
        ),
    ]
