# Generated by Django 4.0.4 on 2022-05-11 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Current price')),
                ('d', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Change')),
                ('dp', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Percent change')),
                ('h', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='High price of the day')),
                ('l', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Low price of the day')),
                ('o', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Open price of the day')),
                ('pc', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Previous close price')),
                ('t', models.PositiveIntegerField(verbose_name='Timestamp')),
            ],
        ),
        migrations.CreateModel(
            name='StockSymbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=255)),
                ('display_symbol', models.CharField(max_length=32)),
                ('figi', models.CharField(max_length=64)),
                ('isin', models.CharField(max_length=32, null=True)),
                ('mic', models.CharField(max_length=32)),
                ('share_class_figi', models.CharField(max_length=64)),
                ('symbol', models.CharField(max_length=32)),
                ('symbol2', models.CharField(max_length=32)),
                ('type', models.CharField(max_length=32)),
            ],
        ),
    ]
